// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Neeeooshka/gopher-club/internal/app"
)

// Injectors from wire.go:

func InitializeApp() (*app.GopherClubApp, func(), error) {
	options := ProvideConfig()
	storage, err := ProvidePostgresStorage(options)
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideZapLogger()
	if err != nil {
		return nil, nil, err
	}
	compressor := ProvideGzipCompressor()
	gopherClubApp := ProvideApp(options, storage, logger, compressor)
	return gopherClubApp, func() {
	}, nil
}
