// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: balance.sql

package sqlc

import (
	"context"
)

const getWithdrawals = `-- name: GetWithdrawals :many
SELECT id, user_id, num, date_withdraw, sum FROM withdrawals WHERE user_id = $1 ORDER BY date_withdraw DESC
`

func (q *Queries) GetWithdrawals(ctx context.Context, userID int) ([]Withdrawal, error) {
	rows, err := q.db.Query(ctx, getWithdrawals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Num,
			&i.DateWithdraw,
			&i.Sum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWithdrawn = `-- name: GetWithdrawn :one
SELECT SUM(sum) AS withdrawn FROM withdrawals WHERE user_id = $1 GROUP BY user_id
`

func (q *Queries) GetWithdrawn(ctx context.Context, userID int) (float32, error) {
	row := q.db.QueryRow(ctx, getWithdrawn, userID)
	var withdrawn float32
	err := row.Scan(&withdrawn)
	return withdrawn, err
}

const withdrawBalance = `-- name: WithdrawBalance :exec
INSERT INTO withdrawals (user_id, num, sum) VALUES ($1, $2, $3)
`

type WithdrawBalanceParams struct {
	UserID int
	Num    string
	Sum    float32
}

func (q *Queries) WithdrawBalance(ctx context.Context, arg WithdrawBalanceParams) error {
	_, err := q.db.Exec(ctx, withdrawBalance, arg.UserID, arg.Num, arg.Sum)
	return err
}
