// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"
)

const addOrder = `-- name: AddOrder :one
WITH ins AS (
    INSERT INTO orders (user_id, num) VALUES ($1, $2)
    ON CONFLICT (num) DO NOTHING
    RETURNING id, user_id, num, date_insert, accrual, status, TRUE AS is_new
)

SELECT id, user_id, num, date_insert, accrual, status, is_new FROM ins
UNION ALL
SELECT id, user_id, num, date_insert, accrual, status, FALSE AS is_new FROM orders WHERE num = $2
LIMIT 1
`

type AddOrderParams struct {
	UserID int
	Num    string
}

type AddOrderRow struct {
	ID         int
	UserID     int
	Num        string
	DateInsert time.Time
	Accrual    float32
	Status     NullOrderStatus
	IsNew      bool
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) (AddOrderRow, error) {
	row := q.db.QueryRow(ctx, addOrder, arg.UserID, arg.Num)
	var i AddOrderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Num,
		&i.DateInsert,
		&i.Accrual,
		&i.Status,
		&i.IsNew,
	)
	return i, err
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, user_id, num, date_insert, accrual, status FROM orders WHERE user_id = $1 ORDER BY date_insert DESC
`

func (q *Queries) ListUserOrders(ctx context.Context, userID int) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Num,
			&i.DateInsert,
			&i.Accrual,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
