// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (login, password) VALUES ($1, crypt($2, gen_salt('des')))
ON CONFLICT (login) DO UPDATE SET login = EXCLUDED.login
RETURNING id, (xmax = 0) AS is_new
`

type AddUserParams struct {
	Login string
	Crypt string
}

type AddUserRow struct {
	ID    int
	IsNew bool
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (AddUserRow, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Login, arg.Crypt)
	var i AddUserRow
	err := row.Scan(&i.ID, &i.IsNew)
	return i, err
}

const authUser = `-- name: AuthUser :one
SELECT id, login, password, balance FROM users u WHERE u.login = $1 AND password = crypt($2, password) LIMIT 1
`

type AuthUserParams struct {
	Login string
	Crypt string
}

func (q *Queries) AuthUser(ctx context.Context, arg AuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, authUser, arg.Login, arg.Crypt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.Balance,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password, balance FROM users u WHERE u.login = $1 LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.Balance,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE users SET balance = balance + $1 WHERE id = $2
`

type UpdateBalanceParams struct {
	Balance float32
	ID      int
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.Balance, arg.ID)
	return err
}
