// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
)

const addCredentials = `-- name: AddCredentials :exec
INSERT INTO user_key_value (user_id, p_name, p_value) VALUES ($1, 'credentials', $2)
`

type AddCredentialsParams struct {
	UserID int
	PValue string
}

func (q *Queries) AddCredentials(ctx context.Context, arg AddCredentialsParams) error {
	_, err := q.db.Exec(ctx, addCredentials, arg.UserID, arg.PValue)
	return err
}

const addUser = `-- name: AddUser :one
INSERT INTO users (login, password) VALUES ($1, $2)
ON CONFLICT (login) DO UPDATE SET login = EXCLUDED.login
RETURNING id, (xmax = 0) AS is_new
`

type AddUserParams struct {
	Login    string
	Password string
}

type AddUserRow struct {
	ID    int
	IsNew bool
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (AddUserRow, error) {
	row := q.db.QueryRow(ctx, addUser, arg.Login, arg.Password)
	var i AddUserRow
	err := row.Scan(&i.ID, &i.IsNew)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT u.id, u.login, u.password, u.balance, up.p_value AS credentials FROM users u
JOIN user_key_value up ON up.user_id = u.id AND p_name = 'credentials'
WHERE u.login = $1
LIMIT 1
`

type GetUserByLoginRow struct {
	ID          int
	Login       string
	Password    string
	Balance     float32
	Credentials string
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.Balance,
		&i.Credentials,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE users SET balance = balance + $1 WHERE id = $2
`

type UpdateBalanceParams struct {
	Balance float32
	ID      int
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.Balance, arg.ID)
	return err
}
