// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	decimal "github.com/shopspring/decimal"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updateOrders = `-- name: UpdateOrders :batchexec
update gopher_orders set status = $1, accrual = $2 where id = $3
`

type UpdateOrdersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdateOrdersParams struct {
	Status  string
	Accrual decimal.Decimal
	ID      int
}

func (q *Queries) UpdateOrders(ctx context.Context, arg []UpdateOrdersParams) *UpdateOrdersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Status,
			a.Accrual,
			a.ID,
		}
		batch.Queue(updateOrders, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateOrdersBatchResults{br, len(arg), false}
}

func (b *UpdateOrdersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdateOrdersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
