// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	decimal "github.com/shopspring/decimal"
)

type GopherOrder struct {
	ID         int
	UserID     int
	Num        string
	DateInsert time.Time
	Accrual    decimal.Decimal
	Status     string
}

type GopherUser struct {
	ID       int
	Login    string
	Password string
	Balance  decimal.Decimal
}

type GopherUserParam struct {
	ID     int
	UserID int
	PName  string
	PValue string
}

type GopherWithdrawal struct {
	ID           int
	UserID       int
	Num          string
	DateWithdraw time.Time
	Sum          decimal.Decimal
}
